"""
Django settings for 国家地表水水质数据爬虫及信息管理系统 project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

import gp.apps

# FILE_UPLOAD_TEMP_DIR = 'file'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-++ap#qdoifi-z6pht_qw^3&7i**!ruko=4#ytqf86bcwi*bqoy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',  # 将Django后台默认模板修改为SimpleUI
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 注册APP gp
    'import_export',
    'gp.apps.GpConfig',
    'background.apps.BackgroundConfig',
]

# 新增导入导出为TRUE
IMPORT_EXPORT_USE_TRANSACTIONS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '国家地表水水质数据爬虫及信息管理系统.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'gp/templates', BASE_DIR / 'background/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '国家地表水水质数据爬虫及信息管理系统.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'graduation',
        'HOST': '127.0.0.1',
        'USER': 'root',
        'PASSWORD': '123456',
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# USE_TZ = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# 配置静态文件路径
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "gp", "static"),
    os.path.join(BASE_DIR, "background", "static"),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 去掉默认的Logo或换成自己的Logo
# SIMPLEUI_LOGO = '../../img/Logo.jpg'

# 隐藏右侧SimpleUI广告连接
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 隐藏首页的快捷操作和最近动作
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False

# 关闭Loading遮罩层
SIMPLEUI_LOADING = False

# 修改左侧菜单首页设置
SIMPLEUI_HOME_PAGE = '/gp/home_page/'  # 指向页面
# SIMPLEUI_HOME_TITLE = '数据爬虫及信息管理系统' # 首页标题
# SIMPLEUI_HOME_ICON = '' # 首页图标

# 设置右上角Home图标跳转链接，会以另外一个窗口打开
SIMPLEUI_INDEX = '/gp/home_page/'

# 指定simpleui默认的主题,指定一个文件名，相对路径就从simpleui的theme目录读取
# SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
SIMPLEUI_DEFAULT_THEME = 'e-blue.css'
# SIMPLEUI_DEFAULT_THEME = 'orange.css'


SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单。

    'system_keep': True,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。 空列表[] 为全部不显示.
    'menu_display': ['用户管理', '权限管理', '数据管理', '数据获取', '数据分析', '数据导出'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    'dynamic': False,
    'menus': [
        {
            'app': 'auth',
            'name': '用户管理',
            'icon': 'fa-solid fa-user-gear',
            'models': [{
                'name': '用户',
                'icon': 'fa fa-user',
                'url': 'auth/user/'
            }]
        },
        {
            'app': 'auth',
            'name': '权限管理',
            'icon': 'fas fa-user-shield',
            'models': [{
                'name': '组',
                'icon': 'fa-solid fa-user-group',
                'url': 'auth/group/'
            }]
        },
        {
            'app': 'auth',
            'name': '数据获取',
            'icon': 'fa-solid fa-file-import',
            'models': [
                {
                    'name': '文件导入',
                    'icon': 'fa-solid fa-file-import',
                    'url': '/gp/upload/',
                },
                {
                    'name': '数据爬取',
                    'icon': 'fa-solid fa-spider',
                    'url': '/gp/crawler/',
                },

            ]
        },
        {
            'name': '数据导出',
            'icon': 'fa-solid fa-file-export',
            'models': [
                {
                    'name': '按时间范围导出',
                    'icon': 'fa-solid fa-chart-circle',
                    'url': '/gp/date_export/',
                },
                {
                    'name': '按流域范围导出',
                    'icon': 'fa-solid fa-chart-circle',
                    'url': '/gp/basin_export/',
                },
                {
                    'name': '按河流范围导出',
                    'icon': 'fa-solid fa-chart-circle',
                    'url': '/gp/river_export/',
                },
                {
                    'name': '按断面范围导出',
                    'icon': 'fa-solid fa-chart-circle',
                    'url': '/gp/section_export/',
                },
            ]
        },
        {
            'name': '数据分析',
            'icon': 'fa-solid fa-chart-simple',
            'models': [
                {
                    'name': '省份时间统计',
                    'icon': 'fa-solid fa-chart-circle',
                    'url': '/gp/statistic/',
                },
                {
                    'name': '城市水质分析',
                    'icon': 'fa-solid fa-chart-circle',
                    'url': '/gp/city_statistic/',
                },
                {
                    'name': '断面时间趋势',
                    'icon': 'fa-solid fa-chart-circle',
                    'url': '/gp/section_statistic/',
                }
            ]
        }
    ],
}

# 添加自定义软件包路径到python路径中
import sys

sys.path.append("D:\毕业设计\国家地表水水质数据爬虫及信息管理系统\my_package")
