# Generated by Django 4.2.3 on 2024-03-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='行政代码'),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='行政代码'),
        ),
    ]
