# Generated by Django 4.2.3 on 2024-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_alter_data_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_time', models.DateTimeField(null=True, verbose_name='检测时间')),
                ('water_type', models.CharField(max_length=30, null=True, verbose_name='水质类别')),
                ('water_temperature', models.FloatField(null=True, verbose_name='水温')),
                ('pH', models.FloatField(null=True, verbose_name='pH')),
                ('dissolved_oxygen', models.FloatField(null=True, verbose_name='溶解氧')),
                ('conductivity', models.FloatField(null=True, verbose_name='电导率')),
                ('turbidity', models.FloatField(null=True, verbose_name='浊度')),
                ('permanganate_index', models.FloatField(null=True, verbose_name='高锰酸钾指数')),
                ('ammonia_nitrogen', models.FloatField(null=True, verbose_name='氨氮')),
                ('total_phosphorus', models.FloatField(null=True, verbose_name='总磷')),
                ('total_nitrogen', models.FloatField(null=True, verbose_name='总氮')),
                ('chlorophyll_alpha', models.FloatField(null=True, verbose_name='叶绿素')),
                ('algal_density', models.FloatField(null=True, verbose_name='藻密度')),
                ('station_status', models.TextField(null=True, verbose_name='站点情况')),
            ],
            options={
                'verbose_name': '数据视图',
                'verbose_name_plural': '水质列表视图',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '数据', 'verbose_name_plural': '水质列表'},
        ),
    ]
