# Generated by Django 4.2.3 on 2024-04-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_dataview_alter_data_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataView',
        ),
    ]
